// <auto-generated />
namespace Bank.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class IsAdminTrueOnAdminUserObject : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsAdminTrueOnAdminUserObject));
        
        string IMigrationMetadata.Id
        {
            get { return "201912072021152_IsAdminTrueOnAdminUserObject"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
